address compilation error in release mode
11,
       inlined from ‘constexpr void
fmt::v9::detail::bigint::assign_pow10(int)’ at
/usr/include/fmt/format.h:2893:11,
       inlined from ‘constexpr void
fmt::v9::detail::bigint::assign_pow10(int)’ at
/usr/include/fmt/format.h:2884:24,
       inlined from ‘constexpr void
fmt::v9::detail::format_dragon(basic_fp<__int128 unsigned>, unsigned
int, int, buffer<char>&,
    int&)’ at /usr/include/fmt/format.h:3011:29:
   /usr/include/c++/13/bits/stl_algobase.h:437:30: error: ‘void*
__builtin_memmove(void*, const void*, long unsigned int)’
   forming offset 4 is out of the bounds [0, 4] [-Werror=array-bounds=]
     437 |             __builtin_memmove(__result, __first, sizeof(_Tp)
* _Num);
         |
~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   cc1plus: all warnings being treated as errors
   gmake[2]: *** [CMakeFiles/vsdf.dir/build.make:121:
CMakeFiles/vsdf.dir/src/online_sdf_renderer.cpp.o] Error 1
   gmake[1]: *** [CMakeFiles/Makefi

    inlined from ‘constexpr void fmt::v9::detail::format_dragon(basic_fp<__int128 unsigned>, unsigned int, int, buffer<char>&, int&)’ at /usr/include/fmt/format.h:3011:29:
/usr/include/c++/13/bits/stl_algobase.h:437:30: error: ‘void* __builtin_memmove(void*, const void*, long unsigned int)’ forming offset 4 is out of the bounds [0, 4] [-Werror=array-bounds=]
  437 |             __builtin_memmove(__result, __first, sizeof(_Tp) * _Num);
      |             ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
[9/10] Building CXX object CMakeFiles/vsdf.dir/src/ffmpeg_encoder.cpp.o
ninja: build stopped: subcommand failed.
Error: Process completed with exit code 1.

https://github.com/jamylak/vsdf/actions/runs/20944451445/job/60184584605?pr=23

Due to how we treat warnings as errors, somehow it finds this issue in
fmt/spdlog libraries